# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    increment_version_number
    build_app
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    upload_to_testflight(changelog: changelog)
  end
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "FMSearch")
    upload_to_app_store
  end
end
